### ISSUE TITLE
Erro 

### ISSUE THREAD

**Issue by natanoliveiracruz** [wgenial/sinesp-consulta-placa#1]
galera ta com problemas achoque a key foi trocada novamente.

**Comment by giovanigenerali** [comment]
Realmente está fora, estou aguardando estabilizar e o pessoal liberar. Se tiver alguma mudança eu faço um fix.

**Comment by giovanigenerali** [comment]
Atualizei o readme com informações de um novo repositório que tem um código em python funcionando.
