### ISSUE TITLE
Possível solução

### ISSUE THREAD

**Issue by joaocalixto** [wgenial/sinesp-consulta-placa#2]
Giovani boa tarde,

Também estou tentando usar o serviço do sinesp, o único indicio que eu achei de chave foi em um arquivo libexternal.so dentro da pasta lib do apk. A chave la dentro era 7lYS859X6fhB5Ow porem o hash gerado não bateu com o hash do apk. Se tiver alguma novidade me avisa.

Obrigado

**Comment by giovanigenerali** [comment]
Atualizei o readme com informações de um novo repositório que tem um código em python funcionando.
